library(data.table)
datesToRead <- difftime(as.POSIXct("2007-02-03"), as.POSIXct("2007-02-01"), units = "mins")
rowsToRead <- as.numeric(datesToRead)
householdDT <- fread(input = "household_power_consumption.txt", sep = ";", skip = "1/2/2007", nrows = rowsToRead, na.strings = c("?", ""))
setnames(householdDT, make.names(colnames(fread("household_power_consumption.txt", sep = ";", nrows = 1, header = T))))
dateTimeXAxisTest <- strptime(paste(householdDT$Date, householdDT$Time), format = "%d/%m/%Y %H:%M:%S")
png("./plot3.png", width = 480, height = 480)
plot(dateTimeXAxisTest <- strptime(x = paste(householdDT$Date, householdDT$Time), format = "%d/%m/%Y %H:%M:%S"), householdDT$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(dateTimeXAxisTest <- strptime(x = paste(householdDT$Date, householdDT$Time), format = "%d/%m/%Y %H:%M:%S"), householdDT$Sub_metering_2, col = "red")
lines(dateTimeXAxisTest <- strptime(x = paste(householdDT$Date, householdDT$Time), format = "%d/%m/%Y %H:%M:%S"), householdDT$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1)
dev.off()
